name: christmas_lights_kata
description: Christmas lights kata
version: 0.1.0

environment:
  sdk: ">=2.18.4 <3.0.0"

dependencies:
  characters: ^1.2.1

dev_dependencies:
  test: ^1.22.0
  very_good_analysis: ^3.1.0
